// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsz2t0xZ6K5LzlUZsxb-276HM4uGxOqjA',
    appId: '1:685900304609:web:ec5a3ce2a218fa84cbe7a0',
    messagingSenderId: '685900304609',
    projectId: 'smapp-16b9e',
    authDomain: 'smapp-16b9e.firebaseapp.com',
    storageBucket: 'smapp-16b9e.firebasestorage.app',
    measurementId: 'G-5C9Q69WGHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX81anyqyN4mmtkwH5Fp0SVVgiXho6VAM',
    appId: '1:685900304609:android:6db314597b8f83ffcbe7a0',
    messagingSenderId: '685900304609',
    projectId: 'smapp-16b9e',
    storageBucket: 'smapp-16b9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlHeEASlt5e4EbCVAOgNzJrMT5voxdr1g',
    appId: '1:685900304609:ios:bedfdf856a36e423cbe7a0',
    messagingSenderId: '685900304609',
    projectId: 'smapp-16b9e',
    storageBucket: 'smapp-16b9e.firebasestorage.app',
    iosBundleId: 'com.example.smapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlHeEASlt5e4EbCVAOgNzJrMT5voxdr1g',
    appId: '1:685900304609:ios:bedfdf856a36e423cbe7a0',
    messagingSenderId: '685900304609',
    projectId: 'smapp-16b9e',
    storageBucket: 'smapp-16b9e.firebasestorage.app',
    iosBundleId: 'com.example.smapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsz2t0xZ6K5LzlUZsxb-276HM4uGxOqjA',
    appId: '1:685900304609:web:8689e677414e8c71cbe7a0',
    messagingSenderId: '685900304609',
    projectId: 'smapp-16b9e',
    authDomain: 'smapp-16b9e.firebaseapp.com',
    storageBucket: 'smapp-16b9e.firebasestorage.app',
    measurementId: 'G-MPQVDCTC4X',
  );
}
